---------------------------
-- Default awesome theme --
---------------------------

font          = sans 8

bg_normal     = #171717
bg_focus      = #524E41
bg_urgent     = #171717
 
fg_normal     = #999999
fg_focus      = #ffffff
fg_urgent     = #ffc500
 
border_width  = 2
border_normal = #151515
border_focus  = #524E41
border_marked = #91231c
 
widget_label = #333333
widget_value = #555555
 
# There are another variables sets
# overriding the default one when
# defined, the sets are:
# [taglist|tasklist]_[bg|fg]_[focus|urgent]
# titlebar_[bg|fg]_[normal|focus]
# Example:
#taglist_bg_focus = #ff0000

# Display the taglist squares
taglist_squares_sel = /opt/local/gentoo/usr/share/awesome/themes/default/taglist/squarefw.png
taglist_squares_unsel = /opt/local/gentoo/usr/share/awesome/themes/default/taglist/squarew.png

tasklist_floating_icon = /opt/local/gentoo/usr/share/awesome/themes/default/tasklist/floatingw.png

# Variables set for theming menu
# menu_[bg|fg]_[normal|focus]
# menu_[border_color|border_width]
menu_submenu_icon = /opt/local/gentoo/usr/share/awesome/themes/default/submenu.png
menu_height   = 15
menu_width    = 100

# You can add as many variables as
# you wish and access them by using
# beautiful.variable in your rc.lua
#bg_widget    = #cc0000

# Define the image to load
titlebar_close_button_normal = /opt/local/gentoo/usr/share/awesome/themes/default/titlebar/close.png
titlebar_close_button_focus = /opt/local/gentoo/usr/share/awesome/themes/default/titlebar/closer.png

# You can use your own command to set your wallpaper
#wallpaper_cmd = awsetbg /opt/local/gentoo/usr/share/awesome/themes/default/background.png

# You can use your own layout icons like this:
layout_fairh = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/fairhw.png
layout_fairv = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/fairvw.png
layout_floating = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/floatingw.png
layout_magnifier = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/magnifierw.png
layout_max = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/maxw.png
layout_tilebottom = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/tilebottomw.png
layout_tileleft = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/tileleftw.png
layout_tile = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/tilew.png
layout_tiletop = /opt/local/gentoo/usr/share/awesome/themes/default/layouts/tiletopw.png

awesome_icon = /opt/local/gentoo/usr/share/awesome/icons/awesome16.png

