#!/bin/zsh

if [[ $OS == Darwin && $EPREFIX == '' ]] then
  # no dircolors on osx
  export CLICOLOR=1
  export LSCOLORS=ExFxCxDxBxegedabagacad
  export ZLSCOLORS=$LSCOLORS
else
  eval "`dircolors`"
  # export LS_COLORS="*.ogm=01;35:${LS_COLORS}"
  export ZLS_COLORS=$LS_COLORS
fi
