#!/bin/zsh

# Locate virtualenvwrapper binary
if [ -f "${EPREFIX}/usr/bin/virtualenvwrapper_lazy.sh" ]; then
    export VENVWRAP="${EPREFIX}/usr/bin/virtualenvwrapper_lazy.sh"
fi

if [ ! -z $VENVWRAP ]; then
    # virtualenvwrapper -------------------------------------------
    # make sure env directory exists; else create it
    [ -d "${HOME}/.cache/pypoetry/virtualenvs" ] || mkdir -p "${HOME}/.cache/pypoetry/virtualenvs"
    export WORKON_HOME="${HOME}/.cache/pypoetry/virtualenvs"
    source $VENVWRAP

    # virtualenv --------------------------------------------------
    export VIRTUALENV_USE_DISTRIBUTE=true

    # pip ---------------------------------------------------------
    export PIP_VIRTUALENV_BASE=$WORKON_HOME
    export PIP_REQUIRE_VIRTUALENV=false
    export PIP_RESPECT_VIRTUALENV=true
    export PIP_DOWNLOAD_CACHE="${HOME}/.pip/cache"
fi
