#!/bin/zsh

source ~/.zsh.d/zaw/zaw.zsh
bindkey -M filterselect '^R' down-line-or-history
bindkey -M filterselect '^S' up-line-or-history
bindkey -M filterselect '^E' accept-search
bindkey '^R' zaw-history
bindkey '^Xa' zaw-applications

zstyle ':filter-select:highlight' matched fg=green
zstyle ':filter-select' max-lines 10 # use 10 lines for filter-select
# zstyle ':filter-select' max-lines -10 # use $LINES - 10 for filter-select
zstyle ':filter-select' rotate-list yes # enable rotation for filter-select
zstyle ':filter-select' case-insensitive yes
zstyle ':filter-select' extended-search yes
