#!/bin/zsh

source ~/.zsh.d/zaw/zaw.zsh
bindkey -M filterselect '^R' down-line-or-history
bindkey -M filterselect '^S' up-line-or-history
bindkey -M filterselect '^E' accept-search
bindkey '^R' zaw-history

zstyle ':filter-select:highlight' matched fg=green
zstyle ':filter-select' max-lines 4
zstyle ':filter-select' case-insensitive yes # enable case-insensitive 
zstyle ':filter-select' extended-search yes # see below
