#! /bin/zsh

if [ x"$HOME" = x ] ; then
  export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
  export HOSTNAME=$(hostname)
fi

export FULLNAME="Reza Jelveh"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

export RXVT_SOCKET=$HOME/.rxvt_socket

export CVS_RSH="ssh"
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export GIT_EDITOR=vim
export VIEW=open
export VISUAL=vim
#export CCACHE_DIR=$HOME/.ccache

export INPUTRC="~/.inputrc"
# export MAIL="${HOME}/mail/inbox"

export RLWRAP_HOME=~/.cache/rlwrap/
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=en_US.UTF-8

export ERL_LIBS=~/git/erlang/libs

export GOPATH=~/git/gocode

export ANDROID_HOME=/opt/android-sdk
RLWRAP_HOME="$HOME/.rlwrap"

export EnableNuGetPackageRestore=true

if [[ $OS == linux ]]; then
  path=($HOME/bin $path $HOME/.gem/ruby/2.0.0/bin $GOPATH/bin)
elif [[ $OS == osx ]]; then
  PATH="$HOME/bin:$PATH"
  PATH="/opt/local/bin:/opt/local/vim/bin:$PATH"
  PATH="/usr/local/bin:$PATH"
  PATH="$PATH:/sbin:/usr/sbin"
  PATH="$PATH:/usr/local/sbin"
  PATH="$PATH:/usr/X11R6/bin"
  PATH="$PATH:/opt/local/sloccount/bin"
  PATH="$PATH:/usr/local/clang/bin"
  export MANPATH=/opt/local/share/man:$MANPATH
fi

export PATH
# less options
LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
export WINDOW_MANAGER=awesome
