#! /bin/zsh

if [ x"$HOME" = x ] ; then
  export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
  export HOSTNAME=$(hostname)
fi

export OS="$(uname)"

export FULLNAME="Reza Jelveh"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

export RXVT_SOCKET=$HOME/.rxvt_socket

export CVS_RSH="ssh"
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export GIT_EDITOR=vim
export VIEW=open
export VISUAL=vim
#export CCACHE_DIR=$HOME/.ccache

export INPUTRC="~/.inputrc"
# export MAIL="${HOME}/mail/inbox"

export RLWRAP_HOME=~/.cache/rlwrap/

export LC_MESSAGES=C
export LC_ALL=en_US.UTF-8

export ERL_LIBS=~/git/erlang/libs

export GOPATH=~/git/gocode

export MC_XDG_OPEN=xdg-open

export EMAIL_CONN_TEST=n

export ANDROID_HOME=/opt/android-sdk
RLWRAP_HOME="$HOME/.rlwrap"

export EnableNuGetPackageRestore=true
export TMUX_POWERLINE_THEME=fishman
export TMUX_POWERLINE_SEG_WEATHER_LOCATION="656958"

# export npm_config_prefix=~/.node_modules

if [[ $OS == Linux ]]; then
  path=($HOME/bin $path $GOPATH/bin $HOME/.node_modules/bin $HOME/.local/bin $HOME/.kube/plugins/jordanwilson230 $HOME/.kube/plugins/local /opt/depot_tools $HOME/.cargo/bin ${HOME}/.krew/bin)
  export VAGRANT_DEFAULT_PROVIDER=libvirt
elif [[ $OS == Darwin ]]; then
  PATH="$HOME/bin:$PATH"
  PATH="/opt/local/bin:/opt/local/vim/bin:$PATH"
  PATH="$GOPATH/bin:$PATH"
  PATH="/usr/texbin:$PATH"
  PATH="$PATH:/sbin:/usr/sbin"
  PATH="$PATH:/usr/local/sbin"
  PATH="$PATH:/usr/X11R6/bin"
  PATH="$PATH:/opt/local/sloccount/bin"
  PATH="$PATH:/usr/local/clang/bin"
  # PATH="$PATH:./node_modules/.bin"
  export MANPATH=/opt/local/share/man:$MANPATH
  PATH="$NPM_PACKAGES/bin:$PATH"
  export MANPATH=$NPM_PACKAGES/share/man:/opt/local/share/man:$MANPATH
fi

export PATH
# less options
LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
export WINDOW_MANAGER=awesome
export MC_SKIN=$HOME/.config/mc/skins/candy256.ini

export XAUTHORITY=~/.Xauthority

# export QT_STYLE_OVERRIDE="GTK+"
# export QT_STYLE_OVERRIDE="GTK+"
[ "$XDG_CURRENT_DESKTOP" = "GNOME" ] && export QT_QPA_PLATFORMTHEME="qt5ct"
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_STYLE_OVERRIDE=kvantum
export BROWSER=xdg-open

export DOTNET_CLI_TELEMETRY_OPTOUT=1

# export DMENU=" dmenu -i -fn '-xos4-terminus-medium-r-*-*-24-*' -nb '#303030' -nf '#909090' -sb '#909090' -sf '#303030'"
# export DMENU="dmenu -i -fn -xos4-terminus-medium-r-*-*-24-* -nb #303030 -nf #909090 -sb #909090 -sf #303030"
export LEDGER_FILE="$HOME/Documents/Tax/ledger/default.ledger"
export ANDROID_SDK_ROOT="$HOME/.local/share/android-sdk"
export MATES_DIR=~/.contacts/
export SXHKD_FIFO=~/.sxhkd_fifo


export BROWSER="xdg-open"

# x11
export PANEL_FIFO=~/.bspwm_fifo
export PANEL_FIFO_SECOND=~/.bspwm_fifo_2
#
# Enable GTK+2 integration for OpenOffice.org, if available.
export SAL_USE_VCLPLUGIN=gtk

export RXVT_SOCKET=$HOME/.rxvt_socket

export VDPAU_DRIVER=va_gl
export LIBVA_DRIVER_NAME=iHD

export SPP_COMMON="$HOME/git/toptal/seismic/seismic-processing-platform/common"

export CM_IGNORE_WINDOW="keepassxc"
export FZF_DEFAULT_COMMAND='rg --files --hidden --follow --glob "!.git/*" --no-messages'

export NNN_USE_EDITOR=1
export NNN_DE_FILE_MANAGER=doublecmd
export NNN_COPIER=~/bin/copier.sh
export NNN_BMS='d:~/Documents;n:~/Nextcloud;g:~/git;s:~/git/toptal/seismic'
export NNN_NOTE="$HOME/.note"
export NNN_COLORS="2136"
export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_ARCHIVE="\\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip|zst)$"
export NNN_PLUG='o:fzopen;m:nmount;x:_chmod +x $nnn;p:preview-tui;P:pdfread;R:git-changes'
export NNN_FIFO="$HOME/nnn.fifo"
# export NNN_FIFO="$HOME/cache/nnn.fifo"
# export NNN_OPENER="/path/to/custom/opener"

export STARDICT_DATA_DIR=~/Documents/Dictionaries
export IDEA_JDK=/usr/lib/jvm/jdk-jetbrains
