#! /bin/zsh

if [ x"$HOME" = x ] ; then
  export HOME=$(cd ~ ; pwd)
fi

if [ x"$HOSTNAME" = x ] ; then
  export HOSTNAME=$(hostname)
fi

export FULLNAME="Reza Jelveh"

#export DEBEMAIL=$EMAIL
#export DEBFULLNAME=$FULLNAME

#export GIT_AUTHOR_NAME=$FULLNAME
#export GIT_COMMITTER_NAME=$FULLNAME
#export GIT_AUTHOR_EMAIL=$EMAIL
#export GIT_COMMITTER_EMAIL=$EMAIL

export RXVT_SOCKET=$HOME/.rxvt_socket

export CVS_RSH="ssh"
export CVSREAD=yes
export MANWIDTH=80
export EDITOR=vim
export GIT_EDITOR=vim
export VISUAL=vim
#export CCACHE_DIR=$HOME/.ccache

export INPUTRC="~/.inputrc"
export MAIL="${HOME}/mail/inbox"

export RLWRAP_HOME=~/.cache/rlwrap/
export GTK_IM_MODULE=xim

export LC_MESSAGES=C
export LC_ALL=

PATH="$HOME/bin:$PATH"
PATH="/opt/local/bin:/opt/local/vim/bin:$PATH"
PATH="/usr/local/bin:$PATH"
PATH="$PATH:/sbin:/usr/sbin:/usr/local/sbin"
PATH="$PATH:/usr/X11R6/bin"
PATH="$PATH:/opt/local/sloccount/bin"
export PATH

if [[ $OS == osx ]]; then
  export MANPATH=/opt/local/share/man:$MANPATH
fi

# less options
LESS=FRSX

# this makes man pages look nicer...
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'

# these are the default arguments to exuberant-ctags
# CTAGS="--c++-kinds=+p --fields=+iaS --extra=+q"
