#! /bin/zsh

# bindkey -v "^[[3~" delete-char
# bindkey -v "^[[5~" backward-word
# bindkey -v "^[[6~" forward-word
# Accept suggestions without leaving insert mode
bindkey '^f' vi-forward-word
# or
bindkey '^f' vi-forward-blank-word

bindkey "^[[A" history-beginning-search-backward
bindkey "^[[B" history-beginning-search-forward
# bindkey "^[[A"  up-line-or-search       # cursor up
# bindkey "^[[B"  down-line-or-search     # <ESC>-

bindkey -v "^A" beginning-of-line
bindkey -v "^E" end-of-line
bindkey -v "^K" kill-line
bindkey -v "^L" clear-screen
# bindkey -v "^R" history-incremental-search-backward
bindkey -v "^U" kill-whole-line
bindkey -v "^V" quoted-insert
#bindkey -v "^W" backward-kill-word

bindkey -v "^N" down-history
bindkey -v "^P" up-history

#  bindkey -v "^[H" run-help
#  bindkey -v "^[h" run-help

# bindkey -v "^[H" beginning-of-line
# bindkey -v "^X" paste-xclip

# Select directory and open a ZSH tab completer
# http://zsh.sourceforge.net/Guide/zshguide06.html#l149
# http://www.refining-linux.org/archives/40/ZSH-Gem-5-Menu-selection/
# http://www.cs.elte.hu/zsh-manual/zsh_14.html#SEC52
#
# - space: advance to the directory and open it for the completion
# - backspace: undo the selection
zmodload zsh/complist
bindkey -M menuselect ' ' accept-and-infer-next-history
bindkey -M menuselect '^?' undo

insert_sudo () { zle beginning-of-line; zle -U "sudo " }
zle -N insert-sudo insert_sudo
bindkey "^[s" insert-sudo

# Meta-u to chdir to the parent directory
bindkey -s '\eu' '^Ucd ..; ls^M'

# If AUTO_PUSHD is set, Meta-p pops the dir stack
bindkey -s '\ep' '^Upopd >/dev/null; dirs -v^M'

bindkey '^R' zaw-history
bindkey '^T' zaw-fasd

# search for file and open in vim
bindkey -s '^p' 'vg^M'
# cd to folder
# bindkey -s '\ec' 'fda^M'

# open editor with v
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line
