#!/bin/zsh

if [[ $OS == osx ]]; then
  export EPREFIX="$HOME/Gentoo"
  PATH_BACK=$PATH

  # export LDFLAGS="-Wl,-search_paths_first -L${EPREFIX}/usr/lib -L${EPREFIX}/lib"
  # export CPPFLAGS="-I${EPREFIX}/usr/include"
  # source /opt/local/gentoo/etc/profile

  if [ -e $EPREFIX/etc/profile.env ] ; then
    . $EPREFIX/etc/profile.env
  fi
  unset RUBYOPT

  PATH="$EPREFIX/usr/bin:$EPREFIX/bin:$EPREFIX/usr/sbin:$EPREFIX/tmp/usr/bin:$EPREFIX/tmp/bin:${EPREFIX}/usr/portage/scripts:${ROOTPATH}:$PATH_BACK"

  alias myoverlay="cd $EPREFIX/usr/local/portage"
fi
