#!/bin/zsh
#cheat補完(sudo gem install cheat)
_cheat () {                                                      
	mkdir -p ~/.zsh/completion                                     
	if [ ! -f ~/.zsh/completion/_cheat ]; then                     
		cheat sheets | grep -v All | sed -e 's/^/compadd /g' > ~/.zsh/completion/_cheat
	fi         

	`cat ~/.zsh/completion/_cheat`
}

compdef _cheat cheat

zstyle ':completion:*:*:task:*' verbose yes
zstyle ':completion:*:*:task:*:descriptions' format '%U%B%d%b%u'

zstyle ':completion:*:*:task:*' group-name ''

alias t=task
proj () {
    t proj:$@
}
compdef _task t=task
