#!/bin/zsh

if [[ $OS == linux && -n $DISPLAY && -x /usr/bin/gpg-agent ]]; then
  # Start the GnuPG agent and enable OpenSSH agent emulation
  gnupginf="${HOME}/.gnupg/gpg-agent.info"
  #
  if pgrep -u "${USER}" gpg-agent >/dev/null 2>&1; then
    eval `cat $gnupginf`
    eval `cut -d= -f1 $gnupginf | xargs echo export`
  else
    eval `gpg-agent --enable-ssh-support --daemon`
  fi
fi
