#!/usr/bin/env zsh
if [ -d $HOME/.ec2 ]; then
    export EC2_HOME=$EPREFIX/usr
    if [[ $OS == osx ]]; then
        export JAVA_HOME=/System/Library/Frameworks/JavaVM.framework/Home
    fi
    export EC2_PRIVATE_KEY=`ls $HOME/.ec2/pk-*.pem`
    export EC2_CERT=`ls $HOME/.ec2/cert-*.pem`
fi
