#!/usr/bin/bash

# if ps aux | grep -q "sxhkd"; then
#     sxhkd -s "$SXHKD_FIFO" &
# fi

# bspc config wm_name LG3D
# bspc config click_to_focus true
# bspc control --adopt-orphans
# bspc config focus_by_distance    true
bspc subscribe monitor_remove | while read -r msg ; do
    bspc monitor -d term code web irssi video 6 steam
done &

wmname LG3D

bspc config external_rules_command "$HOME/bin/bspc_rules"
bspc config border_width		1
bspc config window_gap			12
#bspc config top_padding			28 #xfce
bspc config top_padding			40 #kde
bspc config bottom_padding  -2
bspc config left_padding    -2
bspc config right_padding   -2
bspc config split_ratio			0.52
# bspc config focus_follows_pointer	true
# bspc config focused_border_color	'#66d9ef'
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc monitor -d term code web irssi video 6 steam
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true
bspc config merge_overlapping_monitors true
# bspc monitor DP-1 -d VIII IX X

bspc rule -a Chromium desktop=^3
bspc rule -a Opera desktop=^3
bspc rule -a "Pale moon" desktop=^3 state=floating
bspc rule -a Firefox desktop=^3
bspc rule -a Navigator desktop=^3 state=tiled
bspc rule -a Pidgin desktop=^4
bspc rule -a Wire desktop=^4
bspc rule -a Slack desktop=^4
bspc rule -a Kodi desktop=^5
bspc rule -a KeePassXC desktop=^6 follow=on
bspc rule -a "Jameica 2.6.6" desktop=^6 follow=on
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=true
bspc rule -a Skype floating=on desktop=^10
bspc rule -a Steam floating=on desktop=^7
bspc rule -a dota2 floating=on desktop=^7
bspc rule -a Simple-scan floating=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled desktop=^2
bspc rule -a URxvt:scratchpad state=floating sticky=on
bspc rule -a URxvt:clerk state=floating sticky=on
bspc rule -a Ibus-ui-gtk3 state=floating
bspc rule -a Scp-dbus-service.py state=floating
bspc rule -a Corebird state=floating sticky=on
bspc rule -a Gufw.py state=floating
bspc rule -a Connman-gtk state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a Pinentry state=floating
bspc rule -a smplayer state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a org.remmina.Remmina state=floating
bspc rule -a libreoffice state=tiled
bspc rule -a jetbrains-pycharm desktop=^2
bspc rule -a jetbrains-idea desktop=^2
bspc rule -a jetbrains-idea-ce desktop=^2
bspc rule -a Eclipse desktop=^2
bspc rule -a electrum state=floating sticky=on
bspc rule -a 'in.multico.Main' state=floating sticky=on
bspc rule -a floating               state=floating
bspc rule -a '*:floating'           state=floating
bspc rule -a Steam state=floating desktop=^7
bspc rule -a Com.github.jmoerman.go-for-it state=floating
bspc rule -a Evolution-alarm-notify state=floating
bspc rule -a albert state=floating
bspc rule -a Firefox:Places state=floating
bspc rule -a Lin-HaBu state=floating desktop=^5
# bspc rule -a Catfish state=floating # slack
bspc rule -a chrome-token-signing state=floating
bspc rule -a Io.github.celluloid_player.Celluloid state=floating
bspc rule -a zoom state=floating
bspc rule -a '*:launcher' state=floating
bspc rule -a baka-mplayer state=floating
bspc rule -a Sxiv state=floating
bspc rule -a copyq state=floating
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a Artha state=floating
bspc rule -a '*:line.exe' state=floating
bspc rule -a '*:Toolkit' state=floating
bspc rule -a Autokey-gtk state=floating
bspc rule -a Hopper state=floating
