#! /bin/sh

# sxhkd &

bspc config border_width		1
bspc config window_gap			12
bspc config top_padding			32
bspc config bottom_padding  -2
bspc config left_padding    -2
bspc config right_padding   -2
bspc config split_ratio			0.52
bspc config focus_follows_pointer	true
bspc config click_to_focus true
bspc config focused_border_color	'#66d9ef'
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc monitor -d term web code irssi video 6

bspc rule -a Chromium desktop=^2
bspc rule -a Opera desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Kodi desktop=^5
bspc rule -a keepassxc desktop=^6 follow=on
bspc rule -a crx_nckgahadagoaajjgafhacjanaoiihapd floating=true
bspc rule -a Skype floating=on desktop=^10
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a URxvt:scratchpad state=floating sticky=on
